const Events = {
    GATEWAY_START: 'GATEWAY_START',
    GATEWAY_DONE: 'GATEWAY_DONE',
    PROCESS_TRUCK_START: 'PROCESS_TRUCK_START',
    PROCESS_TRUCK_DONE: 'PROCESS_TRUCK_DONE',
    PROCESS_TRUCK_FAIL: 'PROCESS_TRUCK_FAIL'
};

export default Events;